export enum CompanyStatus {
    TO_BE_VERIFIED = 'to_be_verified',
    CALL_BACK = 'call_back',
    UNREACHABLE = 'unreachable',
    CONVERSATION = 'conversation',
    AGREEMENT = 'agreement',
    DOCUMENTS = 'documents',
    DECLARATION = 'declaration',
    NEW_CLIENT = 'new_client',
    OUR_CLIENT = 'our_client',
    NEXT_CAMPAIGN = 'next_campaign',
    CHEAP_MUNICIPALITY = 'cheap_municipality',
    LEASE_ONLY = 'lease_only',
    DID_IT_THEMSELVES = 'did_it_themselves',
    NOT_A_TARGET = 'not_a_target',
    FEW_VEHICLES = 'few_vehicles',
    CALL_BACK_AGAIN = 'call_back_again',
    NOT_INTERESTED = 'not_interested',
    ACTIVITY = 'activity',
    DOESNT_EXIST = 'doesnt_exist',
    NO_NUMBER = 'no_number',
    OUR_MUNICIPALITY = 'our_municipality',
    RESIGNED = 'resigned',
    SIGNED_AGREEMENT_AND_LEFT = 'signed_agreement_and_left',
    PARTNER = 'partner',
    OFFER = 'offer',
    OTHER = 'other',
}
