export const companyTableOptions = [
    { id: '#id', name: 'ID' },
    { id: 'nextContactDate', name: 'Nast. konakt' },
    { id: 'contactHistories', name: 'Historia kontaktów' },
    { id: 'comment', name: 'Komentarz' },
    { id: 'nip', name: 'NIP' },
    { id: 'name', name: 'Nazwa firmy' },
    { id: 'supply', name: 'Tabor' },
    { id: 'frugality', name: 'Oszczędność' },
    { id: 'status', name: 'Status' },
    { id: 'municipality', name: 'Gmina' },
    { id: 'taxincrease', name: 'Wzrost podatku' },
    { id: 'kitrate', name: 'Zestaw' },
    { id: 'year', name: 'Rok' },
    { id: 'fullName', name: 'Imię i nazwisko' },
    { id: 'role', name: 'Rola' },
    { id: 'phone', name: 'Telefon' },
    { id: 'email', name: 'E-mail' },
    { id: 'activation', name: 'Aktywacja' },
    { id: 'rentalFee', name: 'Czynsz' },
    { id: 'statement', name: 'Deklaracja' },
    { id: 'tractor', name: 'Stawka ciągnik' },
    { id: 'trailer', name: 'Stawka naczepa' },
    { id: 'ourTaxes', name: 'Podatek u nas' },
    { id: 'theirsTaxes', name: 'Podatek u nich' },
    { id: 'tractorAmount', name: 'Ciągniki' },
    { id: 'trailerAmount', name: 'Naczepy' },
    { id: 'otherAmount', name: 'Inne' },
    { id: 'contactPersons', name: 'Osoby kontaktowe' },
]
