import type { SelectOption } from '@/shared/ui/Select/types'
import { CompanyStatus } from '../types/status'

export const companyStatusMap = {
    [CompanyStatus.TO_BE_VERIFIED]: 'DO WERYFIKACJI',
    [CompanyStatus.CALL_BACK]: 'ZADZWOŃ',
    [CompanyStatus.DOESNT_EXIST]: 'NIE ISTNIEJE',
    [CompanyStatus.LEASE_ONLY]: 'TYLKO LEASING',
    [CompanyStatus.NOT_A_TARGET]: 'NIE TARGET',
    [CompanyStatus.LOCAL_PATRIOT]: 'LOKALNY PATRIOTA',
    [CompanyStatus.ACTIVITY]: 'DZIAŁALNOŚĆ',
    [CompanyStatus.SMALL_SAVINGS]: 'MAŁA OSZCZĘDNOŚĆ',
    [CompanyStatus.NOT_INTERESTED]: 'NIEZAINTERESOWANI',
    [CompanyStatus.NEXT_CAMPAIGN]: 'NASTĘPNA KAMPANIA',
    [CompanyStatus.CANNOT_BE_CALLED]: 'NIE ODBIERA',
    [CompanyStatus.UNREACHABLE]: 'BRAK KONTAKTU',
    [CompanyStatus.OTHER]: 'INNY',
    [CompanyStatus.CONVERSATION]: 'ROZMOWA',
    [CompanyStatus.OFFER]: 'OFERTA',
    [CompanyStatus.AGREEMENT]: 'UMOWA',
    [CompanyStatus.DOCUMENTS]: 'DOKUMENTY',
    [CompanyStatus.OUR_CLIENT]: 'NASZ KLIENT',
    [CompanyStatus.RESIGNED]: 'ZREZYGNOWAŁ',
}

export const options: SelectOption[] = [
    {
        id: CompanyStatus.TO_BE_VERIFIED,
        name: companyStatusMap[CompanyStatus.TO_BE_VERIFIED],
        bgColor: 'var(--status-green-bg-color)',
        color: 'var(--status-green-color)',
    },
    {
        id: CompanyStatus.CALL_BACK,
        name: companyStatusMap[CompanyStatus.CALL_BACK],
        bgColor: 'var(--status-green-bg-color',
        color: 'var(--status-green-color)',
    },
    {
        id: CompanyStatus.UNREACHABLE,
        name: companyStatusMap[CompanyStatus.UNREACHABLE],
        bgColor: 'var(--status-orange-bg-color)',
        color: 'var(--status-orange-color)',
    },
    {
        id: CompanyStatus.CONVERSATION,
        name: companyStatusMap[CompanyStatus.CONVERSATION],
        bgColor: 'var(--status-red-bg-color)',
        color: 'var(--status-red-color)',
    },
    {
        id: CompanyStatus.AGREEMENT,
        name: companyStatusMap[CompanyStatus.AGREEMENT],
        bgColor: 'var(--status-blue-bg-color)',
        color: 'var(--status-blue-color)',
    },
    {
        id: CompanyStatus.DOCUMENTS,
        name: companyStatusMap[CompanyStatus.DOCUMENTS],
        bgColor: 'var(--status-green-bg-color)',
        color: 'var(--status-green-color)',
    },
    {
        id: CompanyStatus.DOESNT_EXIST,
        name: companyStatusMap[CompanyStatus.DOESNT_EXIST],
        bgColor: 'var(--status-red-bg-color)',
        color: 'var(--status-red-color)',
    },
    {
        id: CompanyStatus.OUR_CLIENT,
        name: companyStatusMap[CompanyStatus.OUR_CLIENT],
        bgColor: 'var(--status-red-bg-color)',
        color: 'var(--status-red-color)',
    },
    {
        id: CompanyStatus.NEXT_CAMPAIGN,
        name: companyStatusMap[CompanyStatus.NEXT_CAMPAIGN],
        bgColor: 'var(--status-blue-bg-color)',
        color: 'var(--status-blue-color)',
    },
    {
        id: CompanyStatus.LEASE_ONLY,
        name: companyStatusMap[CompanyStatus.LEASE_ONLY],
        bgColor: 'var(--status-green-bg-color)',
        color: 'var(--status-green-color)',
    },
    {
        id: CompanyStatus.NOT_A_TARGET,
        name: companyStatusMap[CompanyStatus.NOT_A_TARGET],
        bgColor: 'var(--status-red-bg-color)',
        color: 'var(--status-red-color)',
    },
    {
        id: CompanyStatus.OFFER,
        name: companyStatusMap[CompanyStatus.OFFER],
        bgColor: 'var(--status-yellow-color)',
        color: 'var(--status-red-color)',
    },
    {
        id: CompanyStatus.NOT_INTERESTED,
        name: companyStatusMap[CompanyStatus.NOT_INTERESTED],
        bgColor: 'var(--status-red-bg-color)',
        color: 'var(--status-red-color)',
    },
    {
        id: CompanyStatus.ACTIVITY,
        name: companyStatusMap[CompanyStatus.ACTIVITY],
        bgColor: 'var(--status-blue-bg-color)',
        color: 'var(--status-blue-color)',
    },
    {
        id: CompanyStatus.RESIGNED,
        name: companyStatusMap[CompanyStatus.RESIGNED],
        bgColor: 'var(--status-gray-bg-color)',
        color: 'var(--status-grey-color)',
    },
    {
        id: CompanyStatus.OTHER,
        name: companyStatusMap[CompanyStatus.OTHER],
        bgColor: 'var(--status-blue-bg-color)',
        color: 'var(--status-blue-color)',
    },
    {
        id: CompanyStatus.LOCAL_PATRIOT,
        name: companyStatusMap[CompanyStatus.LOCAL_PATRIOT],
        bgColor: 'var(--status-blue-bg-color)',
        color: 'var(--status-blue-color)',
    },
    {
        id: CompanyStatus.CANNOT_BE_CALLED,
        name: companyStatusMap[CompanyStatus.CANNOT_BE_CALLED],
        bgColor: 'var(--status-red-bg-color)',
        color: 'var(--status-red-color)',
    },
    {
        id: CompanyStatus.SMALL_SAVINGS,
        name: companyStatusMap[CompanyStatus.SMALL_SAVINGS],
        bgColor: 'var(--status-blue-bg-color)',
        color: 'var(--status-blue-color)',
    },
]
